# Generated by Django 6.0.3 on 2026-03-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiccionarioItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, unique=True)),
                ('unidad_medida', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RequisicionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_rq', models.CharField(choices=[('BIEN', 'Bien'), ('SERVICIO', 'Servicio')], max_length=10)),
                ('centro_costo', models.CharField(choices=[('ACUEDUCTO VISTA HERMOSA', 'Acueducto Vista Hermosa'), ('CLUB LLANEROS', 'Club Llaneros'), ('COVICOL OFICINA ESPERANZA', 'Covicol Oficina Esperanza'), ('COVICOL OFICINA MOLINO', 'Covicol Oficina Molino'), ('COVICOL OFICINA PRIMAVERA', 'Covicol Oficina Primavera'), ('FINCA LA SARITA', 'Finca La Sarita'), ('IE RUBIALES', 'IE Rubiales'), ('IMAGENES DIAGNOSTICAS HDG', 'Imágenes Diagnósticas HDG'), ('IMÁGENES VITAL HDV', 'Imágenes Vital HDV'), ('MANTENIMIENTO BIOMEDICO', 'Mantenimiento Biomédico'), ('MANTENIMIENTO HOSPITALARIO HDV', 'Mantenimiento Hospitalario HDV'), ('OBRA CLINICA VITAL GRANADA', 'Obra Clínica Vital Granada'), ('OBRA UNILLANOS', 'Obra Unillanos'), ('OBRA LLANEROS', 'Obra Llaneros'), ('OBRA PRIMAVERA', 'Obra Primavera'), ('OFICINA COVICOL HDG', 'Oficina Covicol HDG'), ('PARQUES VILLAVICENCIO', 'Parques Villavicencio'), ('PTAP', 'PTAP'), ('SUB ESTACION ELECTRICA', 'Sub Estación Eléctrica'), ('ADECUACIONES HDG', 'Adecuaciones HDG')], max_length=100)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='ALTA', max_length=10)),
                ('titulo_caso', models.CharField(max_length=255)),
                ('observaciones_generales', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
